version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://root:example@mongo:27017/EcoRide?authSource=admin
      - JWT_SECRET=twj1234
      - JWT_EXPIRE=24h
      - CORS_ORIGIN=http://localhost:3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_EMAIL=sanaahamliri413@gmail.com
      - SMTP_PASSWORD=Sffmgh 2004
      - FROM_NAME=HamliriSanaa
      - FROM_EMAIL=hamlirisanaa@gmail.com
      - FILE_UPLOAD_PATH=/app/uploads
      - MAX_FILE_UPLOAD=1000000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
